
import '../global.css'


export const metadata = {
    title: 'chatBot',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico",
  },
}
function layouts({ children }) {

  return (
      <>
         {children}
      </>
    
  )
}

export default layouts
