
import '../global.css'


export const metadata = {
    title: 'chatBot',
    description: 'Generated by create next app',
}
function layouts({ children }) {

  return (
      <>
         {children}
      </>
    
  )
}

export default layouts
